#!/usr/bin/env python3
import asyncio
from tcp import Servidor
from collections import defaultdict
import re
import base64

package = [b'']
users = {} # armazena conexão: user
channels = {} # armazena canais: [users_name]
connections = {} # armazena user: conexão
userChannels = {} # armazena user: [canais]

def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None

def sair(conexao):
    global users
    global connections
    global userChannels
    
    try:
        check = defaultdict(lambda : False)
        for channel in userChannels[users[str(conexao)]]:
            channels[channel].remove(users[str(conexao)])
            for user in channels[channel]:
                if not check[user.lower()]:
                    connections[str(user).lower()].enviar(b':%s QUIT :Connection closed\r\n' % (users[str(conexao)]))
                    check[str(user).lower()] = True
        
        del userChannels[users[str(conexao)]]
        del connections[str(users[str(conexao)]).lower()]
        del users[str(conexao)]
    except:
        pass
                
    
    print(conexao, 'conexão fechada')
    conexao.fechar()

def dados_recebidos(conexao, dados):
    global package
    global users
    global connections
    global userChannels

    # Verificar se o pacote é válido
    if dados == b'':
        return sair(conexao)
    
    # Verificar se o pacote anterior ainda não foi finalizado
    if(package[-1] != b'' and b'\r\n' not in package[-1]):
        package[-1] = package[-1] + dados
        package = package[-1].split(b'\r\n')
    else:
        package = dados.split(b'\r\n')

    # Processar cada pacote
    for i in range(0, len(package)-1):
        
        # Verificação de PING
        if b'ping' in package[i].lower():
            conexao.enviar(b":server PONG server :%s\r\n" % package[i].split(b' ', 1)[1])

        # Verificação de NICK
        if b'nick' in package[i].lower():
            novoNick = package[i].split(b' ')[-1]
            if(str(conexao) in users.keys()): 
                antigoNick = users[str(conexao)]
            else:
                antigoNick = b'*'
            nickValido = True
            if(validar_nome(novoNick)):
                for j in users.values():
                    if j.lower() == novoNick.lower(): nickValido = False
                if(nickValido):
                    users[str(conexao)] = novoNick
                    if(antigoNick == b'*'):
                        conexao.enviar(b':server 001 %s :Welcome\r\n' % novoNick)
                        conexao.enviar(b':server 422 %s :MOTD File is missing\r\n' % novoNick)
                    else:
                        del connections[str(antigoNick).lower()]
                        conexao.enviar(b':%s NICK %s\r\n' % (antigoNick, novoNick))
                    connections[str(novoNick).lower()] = conexao
                else:
                    conexao.enviar(b':server 433 %s %s :Nickname is already in use\r\n' % (antigoNick, novoNick))
            else:
                conexao.enviar(b':server 432 %s %s :Erroneous nickname\r\n' % (antigoNick, novoNick))
        
        # Mensagem privada PRIVMSG
        if b'privmsg' in package[i].lower():
            origem = users[str(conexao)]
            destino = package[i].split(b' ')[1]
            conteudo = package[i].split(b' ')[-1]

            if str(destino)[2] == '#':
                for key in channels.keys():
                    if(destino.lower() == key.lower()):
                        destino = key
                    break
                if(origem.lower() in [value.lower() for value in channels[destino]]):
                    resposta = b':%s PRIVMSG %s %s\r\n' % (origem, destino, conteudo)
                    for user in channels[destino]:
                        if(user.lower() != origem.lower()):
                            connections[str(user).lower()].enviar(resposta)
                
            else:
                if(str(destino).lower() in connections.keys()):
                    resposta = b':%s PRIVMSG %s %s\r\n' % (origem, destino, conteudo)
                    connections[str(destino).lower()].enviar(resposta)
        
        if b'join' in package[i].lower():
            channel = package[i].split(b' ')[-1]
            
            if(str(channel)[2] == '#' and validar_nome(channel[1:])):
                if(channel.lower() not in [value.lower() for value in channels.keys()]):
                    channels[channel] = []
                    
                channels[channel].append(users[str(conexao)])
                
                resposta = b':%s JOIN :%s\r\n' % (users[str(conexao)], channel)
                
                if(users[str(conexao)] not in userChannels.keys()):
                    userChannels[users[str(conexao)]] = []
                userChannels[users[str(conexao)]].append(channel)

                for user in channels[channel]:
                    connections[str(user).lower()].enviar(resposta)

                participants = channels[channel]
                participants.sort()
                base = b':server 353 %s = %s :' % (users[str(conexao)], channel)
                resposta = base
                
                for participant in participants: 
                    if len(resposta) + len(participant) < 510:
                        resposta = resposta + participant + b' '
                    else:
                        conexao.enviar(resposta + b'\r\n')
                        resposta = base + participant + b' '
                
                if(resposta != base): conexao.enviar(resposta + b'\r\n')
                
                conexao.enviar(b':server 366 %s %s :End of /NAMES list.\r\n' % (users[str(conexao)], channel))   
            else:
                conexao.enviar(b':server 403 %s :No such channel\r\n' % (channel))
        
        if b'part' in package[i].lower():
            user = users[str(conexao)]
            channel = package[i].split(b' ')[1]
            for key in channels.keys():
                if(channel.lower() == key.lower()):
                    channel = key
                break
            if(user.lower() in [value.lower() for value in channels[channel]]):
                resposta = b':%s PART %s\r\n' % (user, channel)
                for con in channels[channel]:
                    connections[str(con).lower()].enviar(resposta)
                channels[channel].remove(user)
        
        if package[i] != b'': print(conexao, package[i])
        

def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
